### ISSUE TITLE
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/k14s/homebrew-tap/all.rb

### ISSUE THREAD

**Issue by lemaral** [k14s/homebrew-tap#1]
Issue:
brew tap k14s/tap
==> Tapping k14s/tap
Cloning into '/usr/local/Homebrew/Library/Taps/k14s/homebrew-tap'...
remote: Enumerating objects: 10, done.
remote: Counting objects: 100% (10/10), done.
remote: Compressing objects: 100% (10/10), done.
remote: Total 10 (delta 0), reused 2 (delta 0), pack-reused 0
Unpacking objects: 100% (10/10), done.
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/k14s/homebrew-tap/all.rb
formulae require at least a URL
Error: Cannot tap k14s/tap: invalid syntax in tap!

Work around by cloning and moving all.rb out the way then adding the tap and installing the formulas individually:
brew install ytt kbld kapp kwt

**Comment by cppforlife** [comment]
@lemaral deleted all.rb for now.
