### ISSUE TITLE
linux support

### ISSUE THREAD

**Issue by brandonkal** [k14s/homebrew-tap#2]
I would love to see at linux support. The existing binaries should be marked as macos only as homebrew installs these formulas without warning that they will not function.
This can be automated with goreleaser.

**Comment by cppforlife** [comment]
oh, this is the first time i ve heard that homebrew supports non-osx machines. do you have any links to authoring formulas for linux (seems like they are light on docs)?

**Comment by brandonkal** [comment]
Yes, Homebrew on Linux is great :+1:


See the cuelang/tap/cue formula for example.
Also note that GoReleaser provides a sane default for generating formula. So you could look there for reference as well.

**Comment by cppforlife** [comment]
thanks! ill try to give it a go today.

**Comment by cppforlife** [comment]
@brandonkal add linux binaries. thanks for raising this up!
