### ISSUE TITLE
retapping brew required since the move to develop branch

### ISSUE THREAD

**Issue by ajaysolleti** [k14s/homebrew-tap#3]
Issue: since master branch is no longer present, it breaks the standard `brew update` with an error

```
fatal: couldn't find remote ref refs/heads/master
Error: Fetching /usr/local/Homebrew/Library/Taps/k14s/homebrew-tap failed!
```

Reinstalling by applying the following fixes the issue:

`brew untap k14s/tap`
`brew tap k14s/tap`

**Comment by cppforlife** [comment]
we've moved all repos to develop branch. unfortunately there was no obvious way to make homebrew happy with it. thank you for including untap/tap commands.
